server:
  port: 8090
security:
  user:
    password: none
  sessions: always
  ignored: /favicon.ico,/js/**,/css/**,/webjars/**,/**/*.html
zuul:
  routes:
    notification:
      path: /notification/**
      url: http://localhost:8085/notification
    user:
      path: /user/**
      url: http://localhost:8080/uaa/user
spring:
  oauth2:
   # sso:
   #   loginPath: /login
    #sso:
      #home:
        #secure: false
        #path: /,/**/*.html,/webjars/**
    client:
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
      clientId: my-client-with-registered-redirect
      clientSecret: s1llycrash3s
    resource:
      userInfoUri: http://localhost:8080/uaa/user
logging:
  level:
    org.springframework.security: INFO
quartz:
  enabled: false
learnPullJob:
  frequency: 2000
office365PullJob:
  frequency: 2000
office365PushSubscriptionJob:
  frequency: 2000
