server:
  port: 8090
debug:
security:
  user:
    password: none
zuul:
  routes:
    resource:
      path: /notification/**
      url: http://localhost:8085/notification
    user:
      path: /user/**
      url: http://localhost:8080/uaa/user
spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
      clientId: my-client-with-registered-redirect
      #clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:8080/uaa/user
logging:
  level:
    org.springframework.security: DEBUG
quartz:
  enabled: false
learnPullJob:
  frequency: 2000
office365PullJob:
  frequency: 2000
office365PushSubscriptionJob:
  frequency: 2000
