server:
  port: 8090
debug:
security:
  user:
    password: none
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:8085/notification
    user:
      path: /user/**
      url: http://localhost:8080/uaa/user
spring:
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: http://localhost:8080/uaa/oauth/token
      userAuthorizationUri: http://localhost:8080/uaa/oauth/authorize
      clientId: user
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:8080/uaa/user
    #  jwt:
    #    keyValue: |
    #      -----BEGIN PUBLIC KEY-----
    #      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
    #      -----END PUBLIC KEY-----
logging:
  level:
    org.springframework.security: DEBUG
quartz:
  enabled: true
learnPullJob:
  frequency:  2000
office365PullJob:
  frequency: 2000
office365PushSubscriptionJob:
  frequency: 2000
